### ISSUE TITLE
Итераторы и Генераторы

### ISSUE THREAD

**Issue by qanelph** [CitizenFourCF4/1-pathlib#7]
Теория: https://pythonist.ru/iteratory-i-generatory-v-python/

- [x] Сделать параметр `--text` опциональным
- [x] Если `--text` не передан, нужно сгенерировать его внутри программы
- [x] Реализовать вид генератора (создать массив строк) — однострочный генератор, обернуть в функцию
- [x] Реализовать вид генератора (создать массив строк) — обычный генератор, вместо `return` будет `yield`
- [x] Реализовать вид конткатинатора (массив превратит в строку) -> через for и итерируемый объект, познакомиться с `enumerate`
- [x] Реализовать вид конткатинатора (массив превратит в строку) -> через `join`
- [x] Узнать в чем приемущество генератора над обычным итерируемым объектом

Решение разместить в отдельной ветке, отнаследованной от `main`

**Comment by CitizenFourCF4** [comment]
Вопрос по заданию.
Как лучше сделать?
1. В случае создания однострочного генератора можно сразу, в этой же функции положить сгенерированные строки в массив. Чего нельзя сделать в обычном генераторе.
2. Или же лучше отдельно класть строки в массив в main(), используя данные функции?

**Comment by qanelph** [comment]
Предлагаю сделать функцию, которая получает на вход итерируемый объект и создает по нему массив:

```
def create_list(iterateble_object):
      return [element for element in iterateble_object]
```

1. в первом случае ты передашь туда результат работы однострочного генератора
2. во втором просто генератор

**Comment by CitizenFourCF4** [comment]
спасибо

**Comment by qanelph** [comment]
Чтобы остановить генератор, поставить во внутрь генератора условие остановки по параметру,
а потом используя `functools.partial ` создать функцию, которая будет содержать фиксированный параметр;

так мы превратим генератор в итератор

**Comment by CitizenFourCF4** [comment]
![image](https://user-images.githubusercontent.com/94146075/185394939-4ae856f9-3856-43c0-981b-b8da770ca3c1.png)
